[build]
  publish = "dist"

# Force 404 redirects - override default SPA fallback
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true

# Disable automatic SPA mode
[build.environment]
  SPA_MODE = "false"