[build]
  command = "npm run build && node scripts/generate-sitemap.cjs && cp public/sitemap.xml dist/ || echo 'sitemap skipped'"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
