[build]
  command = "npm run build && node scripts/generate-sitemap.cjs || echo 'sitemap skipped'"
  publish = "dist"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
