[build]
  command = "npm run build && cp public/sitemap.xml dist/ && node scripts/generate-sitemap.cjs || echo 'sitemap skipped'"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
