[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
